# Generated by Django 2.0.5 on 2018-08-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_type',
            field=models.CharField(choices=[('JPG/JPEG', 'jpg'), ('PNG', 'png'), ('GIF', 'gif')], default='JPG/JPEG', max_length=50),
        ),
    ]
